python3 check_statistics.py
python3 scene_preprocessing.py
python3 check_statistics_preprocessed.py
python3 scene_postprocessing.py
python3 obj_visual_postprocessed.py
python3 rel_visual_postprocessed.py
python3 scene_graph_split.py